= コーディングメモ

== 参照資料

|===
|内容 |資料 |リポジトリ

|セッションを用いたログイン管理
|https://www.udemy.com/course/nextjs-react-node-aws-mern-lms-elearning-udemy-clone/[edemy のセクション5および6]
|https://gitlab.com/YoshiK159753/edemy
|===

== コードフォーマット

* ref. https://www.digitalocean.com/community/tutorials/how-to-format-code-with-prettier-in-visual-studio-code-ja[Visual Studio CodeでPrettierを使用してコードをフォーマットする方法]
* ref. https://prettier.io/docs/en/options.html[Prettier - Options]
* ref. https://qiita.com/takeshisakuma/items/bbb2cd2f1c65de70e363[.prettierrc (Qiita記事のオプション一覧日本語版)]

PJ に Prettier をインストール。

[source,bash]
----
npm install prettier -D --save-exact
----

(vscode で)フォーマッターの指定と、保存時のフォーマットを有効化。

[source,json]
.settings.json
----
{
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "editor.formatOnSave": true
}
----

`.prettierrc.json` でフォーマット方法を指定。
格納先は `package.json` と同じ階層。

[source,json]
..prettierrc.json
----
{
  "trailingComma": "es5",
  "tabWidth": 2,
  "semi": true,
  "singleQuote": false
}
----

== 環境変数の読み込みについて

`REACT_APP_XXX` のように `REACT_APP_` のプレフィクスが必要。

[quote]
____
ref. https://create-react-app.dev/docs/adding-custom-environment-variables[Adding Custom Environment Variables]

Your project can consume variables declared in your environment as if they were declared locally in your JS files. By default you will have NODE_ENV defined for you, and any other environment variables starting with REACT_APP_.
____

== 絶対パスによるインポート

* https://create-react-app.dev/docs/importing-a-component#absolute-imports[Absolute Imports]

`package.json` と同じ階層に `jsconfig.json` を置き下記を追加。

[source,json]
----
{
  "compilerOptions": {
    "baseUrl": "src"
  },
  "include": ["src"]
}
----

== IE11 対応(axios)

* https://s8a.jp/no-cache-using-ajax-with-ie11[IE11でAjaxを利用する際にキャッシュされないようにする方法]

何も考えずに IE11 で axios を使うとキャッシュの値が返ってくるため期待した動作とならない。
回避するには URL のクエリパラメタに `?_=[タイムスタンプ]` を追加してキャッシュが効かないようにするとよいらしい。

そこで axios の場合はリクエスト時の Interceptors でタイムスタンプを追加する。
Interceptors の記載箇所は要検討だが、ひとまずトップレベルコンポーネントで処理させればよいのでは。。

[source,javascript]
----
axios.interceptors.request.use(function (config) {
  if (typeof config.params === 'undefined') {
    config.params = {};
  }
  if (typeof config.params === 'object') {
    if (typeof URLSearchParams === 'function' && config.params instanceof URLSearchParams)
      config.params.append('_', Date.now());
    else
      config.params._ = Date.now();
  }

  return config;
});
----

== IE11 対応

* https://create-react-app.dev/docs/supported-browsers-features/[supported-browsers-features]

[source,bash]
.インストール
----
npm install react-app-polyfill
----

[source,javascript]
.index.jsに追記
----
// src/index.js の先頭行に追加する
import 'react-app-polyfill/ie11';
import 'react-app-polyfill/stable';
----

[source,json]
.package.json 書き換え
----
"browserslist": {
  "development": [
    ">0.2%",
    "not dead",
    "not op_mini all"
  ]
}
----
